[package]
name = "rgif"
version = "0.1.0"
authors = ["zhenren <wangweizhen@bilibili.com>"]

[profile.release]
opt-level = 3

[lib]
crate-type = ["cdylib"]

[dependencies]
libc = "0.2.40"
gif = "0.9.2"
